# a lightweight linux distribution
FROM tomcat:9.0-alpine

# maintainer
LABEL maintainer="mixalisverros@hotmail.gr"

# deploy the war into tomcat container
ADD https://github.com/mixaverros88/docker_with_java_and_mysql/blob/master/java/target/RESTfulExample.war /usr/local/tomcat/webapps

# the port which the tomcat is listening inside the container
EXPOSE 8080

# run the tomcat
CMD ["catalina.sh", "run"]